baseURL = "https://blog.fairever.ml"
languageCode = "en-us"
title = "fairever's blog"
theme = "hugo-theme-yinyang"
[params]
headTitle = "fairever"
[[params.socials]]
name = "RSS"
link = "https://blog.fairever.ml/index.xml"
